version: '2'
services:
  idart-java:
    image: esaude-docker-idart-docker.bintray.io/java:1.0.0
    container_name: idart-java
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - idart-postgres
  idart-postgres:
    image: esaude-docker-idart-docker.bintray.io/postgres:1.0.0
    container_name: idart-postgres
  esaude-platform-tomcat:
    image: esaude-docker-platform-docker.bintray.io/tomcat:1.2.6
    ports:
      - "8080:8080"
    container_name: esaude-platform-tomcat
    depends_on:
      - esaude-platform-mysql
  esaude-platform-mysql:
    image: esaude-docker-platform-docker.bintray.io/mysql:1.2.6
    container_name: esaude-platform-mysql
